version: '3'

vars:
  COMPOSE_FILES: "-f docker-compose.yml -f docker-compose.obs.yml"
  OBS_SERVICES: grafana prometheus loki alertmanager nginx-exporter tempo

env:
  MYENV: 'myenv'

dotenv: ['.env']

tasks:
  default:
    cmds:
      - task --list-all
  checkenv:
    desc: "Check different env vars"
    cmds:
      - echo {{.AWS_PROFILE}}
      - echo {{.AWS_ACCOUNT_ID}}
      - echo {{.AWS_ECR_ENV}}
  globalenv:
    cmds:
      - echo $MYENV
    silent: true
  localenv:
    cmds:
      - echo $MYENV
    silent: true
    env:
      MYENV: 'localenv'
  dotenv:
    cmds:
      - echo $ENDPOINT
    silent: true
  setup:
    desc: "Setup tools"
    cmds:
      - brew install uv
      - uv sync --group dev
      - pre-commit install
  up:
    cmds:
      - docker compose {{.COMPOSE_FILES}} up -d --build --no-recreate
  build:
    desc: "Build all containers"
    cmds:
      - docker compose {{.COMPOSE_FILES}} build --no-cache
  down:
    desc: "Bring down all containers but keep volumes"
    cmds:
      - docker compose {{.COMPOSE_FILES}} down --timeout 5 --remove-orphans
  down:v:
    desc: "Bring down all containers and remove volumes"
    cmds:
      - docker compose {{.COMPOSE_FILES}} down -v --timeout 5 --remove-orphans
  up:obs:
    cmds:
      - docker compose {{.COMPOSE_FILES}} up -d --no-recreate {{.OBS_SERVICES}}
  down:obs:
    desc: "Stop only observability stack (Grafana/Prometheus/Loki/Alertmanager...)"
    cmds:
      - docker compose {{.COMPOSE_FILES}} stop {{.OBS_SERVICES}}
      - docker compose {{.COMPOSE_FILES}} rm -f {{.OBS_SERVICES}}
  fix:prom_permission:
    desc: "Fix Prometheus data directory permission"
    cmds:
      - task down:obs
      - docker run --rm -v my_dev_setup_sample_prom-data:/prom busybox sh -c 'chown -R 65534:65534 /prom'
      - task up:obs
  setup:espasswords:
    desc: "Create Kibana user in Elasticsearch"
    cmds:
      - |
        docker compose exec -it elasticsearch \
        bin/elasticsearch-setup-passwords interactive
  restart:app:
    desc: "Restart only the app service"
    cmds:
      - docker compose restart app
  test:
    desc: "Run tests"
    cmds:
      # - OTEL_SDK_DISABLED=true docker compose exec app uv run pytest --tb=short --disable-warnings
      - docker compose exec app uv run pytest --tb=short --disable-warnings
  ecr:
    desc: "Build & push images to ECR"
    cmds:
      - AWS_PROFILE={{.AWS_PROFILE}} AWS_ACCOUNT_ID={{.AWS_ACCOUNT_ID}} ./deploy/push_ecr.sh {{.AWS_ECR_ENV}}
