global:
  scrape_interval: 15s
rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: nginx
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8888"]
    scrape_interval: 5s

  - job_name: otel-collector-app
    static_configs:
      - targets: ["otel-collector:8889"]
    scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
