global:
  scrape_interval: 15s
rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  # Prometheus自身
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: app
    static_configs:
      - targets: ["app:8000"]  # FastAPIなら uvicorn のポートに合わせる

  - job_name: nginx
    static_configs:
      - targets: ["nginx-exporter:9113"]

  # - job_name: cadvisor
  #   static_configs:
  #     - targets: ["cadvisor:8080"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
