from typing import Protocol

from app.domain.common.email import Email
from app.domain.users.user import User


class UsersRepository(Protocol):
    async def save(self, user: User) -> None: ...
    async def find_by_username(self, username: str) -> User | None: ...
    async def exists_by_username(self, username: str) -> bool: ...
    async def exists_by_email(self, email: Email) -> bool: ...
