from typing import Protocol

from app.domain.common.email import Email
from app.domain.users.user import User


class UsersRepository(Protocol):
    def save(self, user: User): ...
    def find_by_username(self, username: str): ...
    def exists_by_username(self, username: str) -> bool: ...
    def exists_by_email(self, email: Email) -> bool: ...
