receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}
  resource:
    attributes:
      - action: upsert
        key: service.namespace
        value: myproj
      - action: upsert
        key: deployment.environment
        value: dev

      - action: insert
        key: service
        from_attribute: service.name
      - action: insert
        key: namespace
        from_attribute: service.namespace
      - action: insert
        key: env
        from_attribute: deployment.environment

      - action: upsert
        key: loki.resource.labels
        value: service,namespace,env

exporters:
  otlp/tempo:
    endpoint: ${TEMPO_HOST}:${TEMPO_PORT}
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: http://${LOKI_HOST}:${LOKI_PORT}/otlp
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  debug:
    verbosity: normal

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/tempo]

    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp/loki]
